keys:
  - &vps age1w5lhtjqnq2d45kgu64xfjgxszzpdnunc9h9q9ylnm5fgtfjpcgrsxzpq0q
  - &pi  age1xc03fkd60zstmu49uw7l4dhnhjeqtkedgtxfkp2ul53nhxfzp4fssyrv7n

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *vps
          - *pi
